name: hospital_dev

services:

  postgres:
    image: postgres:17.7
    container_name: postgres_hospital_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_dev_hospital:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongodb_dev_hospital
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data_dev_hospital:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui_dev_hospital
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
  redis:
    image: redis:8
    restart: always
    volumes:
      - redis_data_dev_hospital:/data
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka_dev_hospital_dev
    restart: always

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - kafka_data_dev_hospital:/tmp/kraft-combined-logs
  api:
    build: ../Clinica
    container_name: hospital_mvc_dev
    restart: always
    depends_on:
      - postgres
      - mongo
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MONGO_URI: ${MONGO_URI}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  email-service:
    build:
      context: ../emailService
      dockerfile: Dockerfile

    container_name: email_service_dev

    restart: always

    depends_on:
      - kafka

    environment:
      SPRING_PROFILES_ACTIVE: dev
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    ports:
      - "8081:8080"
volumes:
  postgres_data_dev_hospital:
  mongo_data_dev_hospital:
  redis_data_dev_hospital:
  kafka_data_dev_hospital: