spring.application.name=hospital-api

spring.profiles.active=dev
spring.flyway.enabled=false

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.expiration=3600000

consulta.duracao-slot-minutos=30

